###########################################################################
#                            STANDARD SETTINGS                            #
###########################################################################
performance_tweak_settings:
  # Server activity will be throttled when the tps is below or at this value (use -1 to disable)
  tpsHaltAt: 15
  # This will notify oped users when the tps is below or at this value
  notifyAdmin: true
  # Broadcast that the server is under load and is halting
  broadcastHalt: false
  # The maximum number of entities that can exist in a small radius (use -1 to disable)
  mobCap: 50
  # The maximum number of explosions that can exist in a small radius (use -1 to disable)
  explosionCap: 50

# [halt_settings] These settings only apply when the server is halted
halt_settings:
  # Should players be allowed to join while the server is halted (users with 'neoperformance.bypass' will still be able to join)?
  allowJoinWhileHalted: true
  haltTeleportation: false
  # [maxSpeed] 3.92000381462276 m/s is the terminal velocity of a player in minecraft (use -1 to disable)
  maxSpeed: -1
  haltExplosions: true
  haltRedstone: true
  # [haltChunkLoading] Use with caution
  haltChunkLoading: false
  # [haltMobSpawning] This will also prevent block breaking and item dropping
  haltMobSpawning: true
  haltInventoryMovement: true #Does not affect players, only hoppers and chests
  haltCommandBlock: true
  haltItemDrops: true
  haltBlockBreaking: true
  haltProjectiles: true
  haltEntityBreeding: false
  haltEntityInteractions: true
  # [haltEntityTargeting] Some lag machines may stop working if this is set to true
  haltEntityTargeting: true
  haltVehicleCollisions: true
  haltBlockPhysics: true
  # Restart server if the server is halted for more than this amount of time in seconds (s) (use -1 to disable)
  haltTimeout: 600

commands:
  #SmartClear
  #Define cluster size for smartClear, using anything below 10 can be dangerous and
  #too high of a value might not do anything
  defaultClusterSize: 15
  #What entities should SmartClear ignore? (underscore or space don't matter, just correct spelling)
  smartClearExcludeEntities:
    - item_frame
    - painting
    - armor_stand

###########################################################################
#        ADVANCED (DON'T TOUCH UNLESS YOU KNOW WHAT YOU ARE DOING)        #
###########################################################################

#If you have a mail server set up, you can use the following settings to send a mail to admins when the server halts. (can be a bit spammy)
#SSL is enabled by default
email_notifications:
  # If you want to use a mail server, set this to true, otherwise it won't work
  use_mail_server: false
  # The mail server hostname
  mail_server_host: smtp.gmail.com
   # The mail server port
  mail_server_port: 587
  # The mail server email address that will be used to send the mail
  mail_server_username: example@gmail.com
  # The mail server password
  mail_server_password: password
  # The recipients
  recipients:
    - "example@gmail.com"
    - "example2@gmail.com"
visual:
  language: en-US